# Generated by Django 3.2.4 on 2021-06-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='4.jpg', upload_to='images/'),
        ),
    ]
