# Generated by Django 3.2.4 on 2021-06-30 17:30

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=slugger.fields.AutoSlugField(default='', populate_from='title'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(default='', max_length=32),
        ),
    ]
